name: sync2gitee

on:
  schedule:
    # UTC 18:00 -> CST (China) 2:00 see https://datetime360.com/cn/utc-cst-china-time/
    - cron: '0 18 * * *' 

jobs:
  sync-to-gitee:
    name: Sync GitHub to Gitee
    runs-on: ubuntu-latest
    steps:
      - name: Git current repository name
        id: info
        uses: actions/github-script@v3.0.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          result-encoding: string
          script: |
            return context.repo.repo;

      - name: Cache src repos
        uses: actions/cache@v2.1.1
        id: cache
        with:
          path: ${{ github.workspace }}/hub-mirror-cache
          key: ${{ runner.os }}-${{ github.repository_owner }}-${{ steps.info.outputs.result }}-cache

      - name: Print the cache status
        if: steps.cache.outputs.cache-hit == 'true'
        run: |
          echo "Cached successfully."

      - name: Mirror the Github repos to Gitee with cache
        uses: Yikun/hub-mirror-action@v0.09
        with:
          src: github/inu1255
          dst: gitee/inu1255
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITEE_TOKEN }}
          account_type: user
          cache_path: /github/workspace/hub-mirror-cache
          static_list: ${{ steps.info.outputs.result }}
          force_update: true

      - name: Print cache path
        run: |
          ls -la ${{ github.workspace }}/hub-mirror-cache